export const newEndpoints = [
  { endPoint: "tropical_transits/monthly", name: "Monthly Tropical Transits" },
  { endPoint: "tropical_transits/weekly", name: "Weekly Tropical Transits" },
  { endPoint: "tropical_transits/daily", name: "Daily Tropical Transits" },
];


export const apiEndpoints = [
  { endPoint: "horo_chart/D-chart", name: "Horoscope Chart" },
  { endPoint: "current_chardasha", name: "Chardasha" },
  { endPoint: "planets", name: "Planets" },
  { endPoint: "astro_details", name: "Astrology Details" },
  { endPoint: "birth_details", name: "Birth Details" },
  { endPoint: "planets/extended", name: "Extended Planets" },
  { endPoint: "general_house_report/sun", name: "General House Report (Sun)" },
  { endPoint: "general_rashi_report/sun", name: "General Rashi Report (Sun)" },
  { endPoint: "general_ascendant_report", name: "General Ascendant Report" },
  { endPoint: "general_nakshatra_report", name: "General Nakshatra Report" },
  { endPoint: "planet_nature", name: "Planet Nature" },
  { endPoint: "bhav_madhya", name: "Bhav Madhya" },
  { endPoint: "ghat_chakra", name: "Ghat Chakra" },
  { endPoint: "ayanamsha", name: "Ayanamsha" },
  { endPoint: "kalsarpa_details", name: "Kalsarpa Details" },
  { endPoint: "manglik", name: "Manglik" },
  { endPoint: "sadhesati_current_status", name: "Sadhesati Current Status" },
  { endPoint: "sadhesati_life_details", name: "Sadhesati Life Details" },
  { endPoint: "pitra_dosha_report", name: "Pitra Dosha Report" },
  { endPoint: "biorhythm", name: "Biorhythm" },
  { endPoint: "moon_biorhythm", name: "Moon Biorhythm" },
  { endPoint: "lalkitab_horoscope", name: "Lalkitab Horoscope" },
  { endPoint: "lalkitab_debts", name: "Lalkitab Debts" },
  { endPoint: "lalkitab_remedies/sun", name: "Lalkitab Remedies (Sun)" },
  { endPoint: "lalkitab_houses", name: "Lalkitab Houses" },
  { endPoint: "lalkitab_planets", name: "Lalkitab Planets" },
  { endPoint: "puja_suggestion", name: "Puja Suggestion" },
  { endPoint: "basic_gem_suggestion", name: "Basic Gem Suggestion" },
  { endPoint: "rudraksha_suggestion", name: "Rudraksha Suggestion" },
  { endPoint: "sadhesati_remedies", name: "Sadhesati Remedies" },
  { endPoint: "horo_chart_extended/D-chart", name: "Horoscope Chart Extended" },
  { endPoint: "daily_nakshatra_prediction", name: "Daily Nakshatra Prediction" },
  { endPoint: "daily_nakshatra_prediction/next", name: "Next Daily Nakshatra Prediction" },
  { endPoint: "daily_nakshatra_prediction/previous", name: "Previous Daily Nakshatra Prediction" },
  { endPoint: "daily_nakshatra_consolidated", name: "Daily Nakshatra Consolidated" },
  { endPoint: "planet_ashtak/sun", name: "Planet Ashtak (Sun)" },
  { endPoint: "sarvashtak", name: "Sarvashtak" },
  { endPoint: "current_vdasha_all", name: "Current Vdasha All" },
  { endPoint: "major_vdasha", name: "Major Vdasha" },
  { endPoint: "current_vdasha", name: "Current Vdasha" },
  { endPoint: "current_vdasha_date", name: "Current Vdasha Date" },
  { endPoint: "varshaphal_year_chart", name: "Varshaphal Year Chart" },
  { endPoint: "varshaphal_month_chart", name: "Varshaphal Month Chart" },
  { endPoint: "varshaphal_details", name: "Varshaphal Details" },
  { endPoint: "varshaphal_planets", name: "Varshaphal Planets" },
  { endPoint: "varshaphal_muntha", name: "Varshaphal Muntha" },
  { endPoint: "varshaphal_mudda_dasha", name: "Varshaphal Mudda Dasha" },
  { endPoint: "varshaphal_panchavargeeya_bala", name: "Varshaphal Panchavargeeya Bala" },
  { endPoint: "varshaphal_harsha_bala", name: "Varshaphal Harsha Bala" },
  { endPoint: "varshaphal_saham_points", name: "Varshaphal Saham Points" },
  { endPoint: "varshaphal_yoga", name: "Varshaphal Yoga" },
  { endPoint: "kp_planets", name: "KP Planets" },
  { endPoint: "kp_house_cusps", name: "KP House Cusps" },
  { endPoint: "kp_birth_chart", name: "KP Birth Chart" },
  { endPoint: "kp_house_significator", name: "KP House Significator" },
  { endPoint: "kp_planet_significator", name: "KP Planet Significator" },
  { endPoint: "basic_panchang/sunrise", name: "Basic Panchang (Sunrise)" },
  { endPoint: "basic_panchang", name: "Basic Panchang" },
  { endPoint: "advanced_panchang/sunrise", name: "Advanced Panchang (Sunrise)" },
  { endPoint: "advanced_panchang", name: "Advanced Panchang" },
  { endPoint: "planet_panchang/sunrise", name: "Planet Panchang (Sunrise)" },
  { endPoint: "planet_panchang", name: "Planet Panchang" },
  { endPoint: "chaughadiya_muhurta", name: "Chaughadiya Muhurta" },
  { endPoint: "hora_muhurta", name: "Hora Muhurta" },
  { endPoint: "hora_muhurta_dinman", name: "Hora Muhurta Dinman" },
  { endPoint: "panchang_chart", name: "Panchang Chart" },
  { endPoint: "panchang_chart/sunrise", name: "Panchang Chart (Sunrise)" },
  { endPoint: "find_nakshatra/ashwini", name: "Find Nakshatra (Ashwini)" },
  { endPoint: "tamil_month_panchang", name: "Tamil Month Panchang" },
  { endPoint: "tamil_panchang", name: "Tamil Panchang" },
  { endPoint: "panchang_festival", name: "Panchang Festival" },
  { endPoint: "major_chardasha", name: "Major Chardasha" },
  { endPoint: "sub_chardasha/aries", name: "Sub Chardasha (Aries)" },
  { endPoint: "major_yogini_dasha", name: "Major Yogini Dasha" },
  { endPoint: "sub_yogini_dasha", name: "Sub Yogini Dasha" },
  { endPoint: "current_yogini_dasha", name: "Current Yogini Dasha" },
  { endPoint: "numero_table", name: "Numero Table" },
  { endPoint: "numero_report", name: "Numero Report" },
  { endPoint: "numero_fav_time", name: "Numero Favorite Time" },
  { endPoint: "numero_place_vastu", name: "Numero Place Vastu" },
  { endPoint: "numero_fasts_report", name: "Numero Fasts Report" },
  { endPoint: "numero_fav_lord", name: "Numero Favorite Lord" },
  { endPoint: "numero_fav_mantra", name: "Numero Favorite Mantra" },
  { endPoint: "numero_prediction/daily", name: "Numero Prediction (Daily)" },
  { endPoint: "geo_details", name: "Geo Details" },
  { endPoint: "timezone", name: "Timezone" },
  { endPoint: "timezone_with_dst", name: "Timezone with DST" },
  { endPoint: "match_birth_details", name: "Match Birth Details" },
  { endPoint: "match_ashtakoot_points", name: "Match Ashtakoot Points" },
  { endPoint: "match_obstructions", name: "Match Obstructions" },
  { endPoint: "match_astro_details", name: "Match Astrology Details" },
  { endPoint: "match_planet_details", name: "Match Planet Details" },
  { endPoint: "match_manglik_report", name: "Match Manglik Report" },
  { endPoint: "match_making_report", name: "Match Making Report" },
  { endPoint: "match_simple_report", name: "Match Simple Report" },
  { endPoint: "match_making_detailed_report", name: "Match Making Detailed Report" },
  { endPoint: "match_dashakoot_points", name: "Match Dashakoot Points" },
  { endPoint: "match_percentage", name: "Match Percentage" },
  { endPoint: "partner_report", name: "Partner Report" },
  { endPoint: "papasamyam_details", name: "Papasamyam Details" }
];
